<?php

/** 
* hook_form_alter(&$form_state, $form_id) 
*/

/**
* function dosomething_quiz_form_alter(&$form, &$form_state, $form_id) {
*  dsm ($form_id);
* }
*/

// replace '3' with the webform id
function dosomething_quiz_form_webform_client_form_3_alter(&$form, &$form_state) {
  $form ['#submit'][] = 'dosomething_quiz_result_redirect';
}
/** 
* Count number of occurrences for each choice
*/
function dosomething_quiz_result_redirect(&$form, &$form_state) { 
  $a_count = 0;
  $b_count = 0;
  $c_count = 0;
  $d_count = 0;
  foreach ($form_state['values']['submitted'] as $answer) {
    switch ($answer) {
	  case 'a':
	    $a_count++;
		break;
	  case 'b':
	    $b_count++;
		break;
	  case 'c':
	    $c_count++;
		break;
	  case 'd':
	    $d_count++;
		break;
	}	
  }  
/** 
* Count the result that has the maximum number of choices then redirect to result page. 
* In case of tie it will redirect to the first result.
*/  
  $max = max($a_count, $b_count, $c_count, $d_count);
  if ($a_count == $max) {
  // result a page
    drupal_goto('content/result-a');
  }
  else if ($b_count == $max) {
  // result b page
    drupal_goto('content/result-b');  
  }
  else if ($c_count == $max) {
  // result c page
    drupal_goto('content/result-c');  
  }
  else if ($d_count == $max) {
  // result d page
    drupal_goto('content/result-d');  
  }  
}