<?php

/* define webform id */

define('QUIZ_ID', '3');

/** 
* hook_form_alter(&$form_state, $form_id) 
*/


/* hook_webform_select_options_info(). */
function hook_webform_select_options_info() {
  $items = array();
  
  $items['questions'] = array{
  'title' => t('Questions')
  'options callback' => webform_options_question',
  'file' => /includes/webform.options.inc',
  );

/*hook_webform_submission_insert($node, $submission) */
function dosomething_quiz_submission_insert($node, $submission) {
 if ($node->nid == QUIZ_ID) {
   if ($submission


